### PR TITLE
a few small updates to the envt, earthpy pip and nodefaults

### PR DESCRIPTION
**Pull request by lwasser**
nodefaults is causing issues with local installs of the envt so removing it from this particular repo.
ensuring earthpy is installed via pip given the newest releases

### CODE REVIEW

**Comment by lwasser** [comment]
wow - you can see the docker cloud build here now!! this is pretty cool!

**Comment by lwasser** [comment]
hey @mbjoseph ive had a few people try to install this envt with the nodefaults flag and it failed. when i remove it it works. I tried to update the envt to 
1. use the more current version of earthpy and 
2. to fix the nodefaults issue but now docker is failing. it seems to be failing when importing rasterio WHICH could be that nodefaults issue...

any thoughts on how to fix things for both docker AND users wanting to install the envt??

**Comment by mbjoseph** [comment]
Hey @lwasser do you know how the environment installation fails when removing the default channel? Any consistency in which packages raise errors, and which operating systems/conda versions are being used?

**Comment by joemcglinchy** [comment]
Here is what I see on windows, Anaconda3 for python 3.7:

```
conda env create -f environment.yml
Solving environment: failed
ResolvePackageNotFound:
  - seaborn
  - patsy
  - scipy
  - seaborn
  - statsmodels
  - scikit-image
  - numpy=1.10
  - scikit-image
  - scipy
  - cartopy
  - numpy=1.10
  - cartopy
  - scipy
  - geopandas
  - gdal==1.11.4
  - geopandas
  - pysal
  - scipy
  - geopandas
  - pysal
  - seaborn
  - patsy
  - geopandas
  - pysal
  - seaborn
  - statsmodels
  - contextily
  - cartopy
  - numpy=1.10
  - contextily
  - cartopy
  - scipy
  - pysal
  - scipy
  - pysal
  - seaborn
  - patsy
  - pysal
  - seaborn
  - statsmodels
```

**Comment by mbjoseph** [comment]
@joemcglinchy what version of conda are you using? `conda --version`

**Comment by lwasser** [comment]
This is the issue (what joe presented above) that GIna ran into as well.

**Comment by joemcglinchy** [comment]
updated conda to most recent version, here is what worked for me. If I remove `no-defaults` from channels, the environment installs everything but `earthpy`. That part of the enviornment creationwas trying to reinstall rasterio again and failing. with this error message:

```
Collecting rasterio (from earthpy->-r C:\software\eapy\earth-analytics-python-env\condaenv.5zxul11k.requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/b4/0f/c5a412208f217bba892e5482c1129df29bdfe474a069aba36407ee68c518/rasterio-1.0.21.tar.gz
    Complete output from command python setup.py egg_info:
    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.
    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
```

A fix was to activate the environment and `pip install earthpy`. This resulted in a clean and importable installation of earthpy.

**Comment by mbjoseph** [comment]
Just so we avoid this issue down the road, I opened an issue to remind us to test environment creation across platforms: https://github.com/earthlab/earth-analytics-python-env/issues/39

**Comment by mbjoseph** [comment]
Joe and I are still digging into this, but one thing that stood out is that there are packages being installed via `pip` that are available on conda-forge. These can be moved to the `dependencies:` section:

- nbgrader
- mne (or delete this? It is described as Magnetoencephalography (MEG) and Electroencephalography (EEG) in Python here: https://anaconda.org/conda-forge/mne)
- tqdm
- kiwisolver
- scikit-learn (listed as `sklearn` currently under the `pip` section)

This might not solve the problem completely, but it's worth a try @lwasser

**Comment by joemcglinchy** [comment]
something I noticed was scikit-learn is installed by the conda base environment. perhaps it isn't needed for the environment file?

**Comment by lwasser** [comment]
ok @joemcglinchy should i remove it then? @mbjoseph i can't see if the docker container builds now as appveyer seems to be attempting to run here.

**Comment by lwasser** [comment]
also just a note that those installs are not conda-forge it seems in the base envt. but it is worth a try to remove it.

**Comment by lwasser** [comment]
it looks like scikit image is also in the native base conda install. perhaps remove both?

**Comment by mbjoseph** [comment]
@lwasser the automated build on Docker Hub is still happening, but it is slower to show up than AppVeyor. As both are failing, I won't review this now. 

In the future if you want to test the Docker build locally, you can run: 

```bash
docker build -t earthlab/earth-analytics-python-env .
```

**Comment by lwasser** [comment]
ok i have tested this on windows and mac and it installs. updating the environment for the time being. will work on appveyor next.

**Pull request merged**
