### PR TITLE
starting to clean up the ea envt

### PR DESCRIPTION
**Pull request by lwasser**
@kcranston here is my start at cleaning up the envt.

some of these packages are ALREADY in the conda install. so we might not need them in this YAML but want them in our docker container 

i'm not sure what is best

1. include what we need here even if it's in the conda install hat students use and because we use conda forge as the priority channel. rasterio is an example of this 
2. remove them here but install via the dockerfile for the hub

@ocefpaf what do you suggest in the case where we are using the continuum download of anaconda for our classes. We install this environment on TOP of that download. some packages like rasterio are already in there.

however we also use this same environment for our docker container on our jupyterhub. in that example we are using a more minimal miniconda base with jupyter on top and might need to install rasterio for example there. Should i consider installing some things like rasterio only in the dockerfile? what is the best practice from conda-forge's perspective?

### CODE REVIEW

**Comment by ocefpaf** [comment]
> @ocefpaf what do you suggest in the case where we are using the continuum download of anaconda for our classes. We install this environment on TOP of that download. some packages like rasterio are already in there.

I don't recommend using the Anaconda Distribution at all in any case. I always prefer miniconda and install everything, even if you are using just `defaults` and nothing comes using `conda-forge`, because it is safer, faster, and all the packages explicitly declared in an env file.

The argument for using `conda-forge` instead of `defaults` as the main package provider is about having the latest packages, and some packages that are not in `defaults`. For example `rasterio` on `defaults` is version `1.0.21` while `conda-forge` have `1.0.24`. Also, `defaults` `gdal` is `2.3.3` while we have both `2.4.2` and `3.0.1`. Note that latest does not mean it is better! But if you do need the latest then you need `conda-forge`.

**Comment by lwasser** [comment]
Current issue when installing over miniconda: when launching jupyterlab:

`Could not determine jupyterlab build status without nodejs`

**Comment by kcranston** [comment]
If earthpy is on the list of packages, then we don't need rasterio and geopandas here, right?

Also, are we using JupyterLab in any of the courses?

**Comment by lwasser** [comment]
@kcranston  good call. i haven't tested the envt without installing geopandas and earthpy explicetly BUT it would install much faster that way. should we try to remove them?

i'd like to include jupyterlab because it's easy to switch between lab and notebooks locally and i'd really like them to have that option. does lab work in the hub?? i just have no idea but i thijnk things are moving towards lab so i'd like lab there in the install.

**Pull request merged**
