### PR TITLE
[WIP] Remove Dockerfile and use repo2docker instead

### LINKED ISSUE #12: Switch to repo2docker?
Hello all,

I am new here 👋! Trying to get up to speed with things.

Is there a reason to have a `Dockerfile` that you created by hand? Depending on what it is needed for it might be easier to switch to http://repo2docker.readthedocs.io/ which takes care of creating containers for you (without you having to write a `Dockerfile`).

Right now it looks like that as a student all I need is the `environment.yml` and `conda` to get setup. In my experience student's are good at getting going with conda, but if we need them to use docker things get slower/more questions/mistakes.

If the reason to have a `Dockerfile` is so we can use this for JupyterHub and/or Binder I'd suggest ditching it because both JHub and mybinder.org use repo2docker, so we can generate the container image from the `environment.yml`.

### PR DESCRIPTION
**Pull request by betatim**
Short exploration on seeing how far you get with using `repo2docker`.

For me running `repo2docker --ref e287c39f62f290e3b6927da08c81586f647d5a4c https://github.com/betatim/earth-analytics-python-env/` takes a while but eventually launches a jupyter notebook in a docker container. The URL it prints has the same problem as you mentioned in another issue about having the wrong hostname. Something to investigate.

Before merging this there are a few things to sort out so this is still work in progress (WIP)

closes #12

### CODE REVIEW

**Comment by betatim** [comment]
Interesting observation: if I use exactly the same docker and repo2docker versions then `repo2docker https://github.com/binder-examples/requirements` will print a useful URL at the end of the process that you can just copy&paste. Something to look into.

**Comment by lwasser** [comment]
Ok i need to understand this. Should i be able to use the above command? what is that hash?
When i try to run the code above 
`epo2docker --ref e287c39f62f290e3b6927da08c81586f647d5a4c https://github.com/betatim/earth-analytics-python-env/` i get: 

screen shot 2018-06-06 at 12 08 52 pm
 
what am i missing? i'm certain i just don't get how repo2docker works

**Comment by betatim** [comment]
The hash is only needed because we don't want to build what is in the `master` branch of the repo. A slightly clunky way of saying "build what is in the repo2docker branch" of the repository.

It will print a whole bunch of text like what is in your screenshot. It is mostly the output of docker building the image.

It will take a while but eventually it should print something like:
```
Removing intermediate container 09bc0d6fef09
 ---> e1183b1b4fae
{"aux": {"ID": "sha256:e1183b1b4fae5cfd6afd2c0731d4d01dc8dbced93258294cda48bab7cfd631e3"}}Successfully built e1183b1b4fae
Successfully tagged r2d-2e1528306074:latest
[I 17:48:39.116 NotebookApp] [nb_conda_kernels] enabled, 3 kernels found
[I 17:48:39.136 NotebookApp] Writing notebook server cookie secret to /home/thead/.local/share/jupyter/runtime/notebook_cookie_secret
[I 17:48:39.777 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.0
[I 17:48:39.837 NotebookApp] JupyterLab beta preview extension loaded from /srv/conda/lib/python3.6/site-packages/jupyterlab
[I 17:48:39.841 NotebookApp] JupyterLab application directory is /srv/conda/share/jupyter/lab
[I 17:48:40.131 NotebookApp] [nb_conda] enabled
[I 17:48:40.143 NotebookApp] nteract extension loaded from /srv/conda/lib/python3.6/site-packages/nteract_on_jupyter
[I 17:48:40.159 NotebookApp] Serving notebooks from local directory: /home/thead
[I 17:48:40.159 NotebookApp] 0 active kernels
[I 17:48:40.159 NotebookApp] The Jupyter Notebook is running at:
[I 17:48:40.159 NotebookApp] http://145be8928013:52716/?token=760db11a3b6c1d3276e58916002e85174139c8809a7b90f7
[I 17:48:40.159 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 17:48:40.160 NotebookApp] No web browser found: could not locate runnable browser.
[C 17:48:40.160 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://145be8928013:52716/?token=760db11a3b6c1d3276e58916002e85174139c8809a7b90f7&token=760db11a3b6c1d3276e58916002e85174139c8809a7b90f7
```
You can now take that URL and paste it into a browser (replacing the `145be8928013` with `localhost`).

For practice `repo2docker https://github.com/binder-examples/requirements` is better as it doesn't take so long to build.

**Comment by lwasser** [comment]
yes. this still doesn't work for me @betatim perhaps i can show you when we chat this week if there is time. i wonder if it's a permissions issue? It hangs and fails here:
```
Step 12/31 : RUN adduser --disabled-password     --gecos "Default user"     --uid ${NB_UID}     ${NB_USER}
 ---> Running in 8459215b4438
Adding user `lewa8222' ...
Adding new group `lewa8222' (550073352) ...
Adding new user `lewa8222' (550073352) with group `lewa8222' ...
Creating home directory `/home/lewa8222' ...
Copying files from `/etc/skel' ...
```

it's been running for maybe 40 minutes.
I ran: repo2docker `https://github.com/binder-examples/requirements`

**Comment by betatim** [comment]
That is a bug in `repo2docker`. There is a fairly long discussion [here](https://github.com/jupyter/repo2docker/issues/223#issuecomment-393699974) but the TL;DR is `repo2docker --user-id 1000 <more arguments here>` fixes this particular problem.

It seems to be connected to user accounts on people's machines being somehow centrally managed and having very large user IDs. Still trying to figure out what the real solution for repo2docker is. The work around of providing a UID on the command-line seems to work.

---

I think there are two things to think about: 

1. building a docker image that works with JupyterHub; and
1. how users setup an equivalent environment locally. 

for 1. I would use repo2docker to build the image from a set of files that are easier to edit for humans. Then push that image to docker hub. This should all be done automagically by Travis.

For 2. I wouldn't use `repo2docker`. Right now I think the easiest thing to do is recommend to people to use `conda` and the `environment.yml` to create a new environment. Maybe at a later stage where we can't do everything via `conda` we can switch to instructions on how to use the docker image built as part of 1. by pulling it from docker hub.

What do you think of that?

**Pull request closed without merging**
